server:
  port: ${PORT:8761}

spring:
  application:
    name: discovery-server

logging:
  level:
    org.springframework.cloud.netflix.eureka: TRACE

eureka:
  instance:
    hostname: localhost
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://${eureka.instance.hostname}:${server.port}/eureka/

