spring:
  application:
    name: gateway-service

server:
  port: 8080

eureka:
  client:
    registerWithEureka: false
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

zuul:
  sensitiveHeaders: Cookie,Set-Cookie,Authorization
  ignoredServices: '*'
  ribbon:
    eager-load:
      enabled: true
  routes:
    library-service:
      path: /**
      url: http://localhost:8090
      stripPrefix: true
      serviceId: library-service

    oauth-service:
      path: /oauth/**
      url: http://localhost:8070
      stripPrefix: true
      serviceId: oauth-service


security:
  oauth2:
    client:
      access-token-uri: http://localhost:8070/oauth/token
      client-secret: user
      id: user
    resource:
      jwt:
        key-value: 123

