version: '3'
services:
  postgres:
    image: postgres
    environment:
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: postgres
      POSTGRES_DB: book
    ports:
      - "5432:5432"
    restart: always
    networks:
      - nw
  app:
    build:
      context: .
      dockerfile: Dockerfile

    environment:
      DB_DRIVER: org.postgresql.Driver
      DB_URL: jdbc:postgresql://postgres:5432/book
      DB_USERNAME: postgres
      DB_PASSWORD: postgres
      WAIT_FOR: postgres:5432
    links:
      - postgres
    networks:
      - nw
    ports:
      - "8080:8080"

networks:
  nw:

