server:
  port: 8070

spring:
  application:
    name: oauth-service
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    service-url:
      defaultZone: http://localhost:8761/eureka/

security:
  oauth2:
    resource:
      jwt:
        key-value: 123
