server:
  port: 8090

spring:
  application:
    name: library-service

logging:
    level:
      org.springframework.security: TRACE

eureka:
  client:
    fetch-registry: false
    register-with-eureka: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

