server:
  port: 8090

spring:
  application:
    name: library-service

  h2:
    console:
      enabled: true
      path: /h2-console
logging:
    level:
      org.springframework.security: TRACE

eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    serviceUrl:
      defaultZone: http://localhost:8761/eureka/

